# Site Settings
title:               Vikas Yadav
tagline:             DL/RL enthusiast
description:
baseurl:            "/"
url:                "https://vy007vikas.github.io"
github:
  url:               "https://vy007vikas.github.io/"
author:
  name:              "Vikas Yadav"
  email:             "vikasyadav.iitr@gmail.com"
  twitter:           "vy007vikas"
  instagram:         "vy007vikas"
  github:            "vy007vikas"
  facebook:          "wicked.yadav"
  linkedin:          "vikas-yadav-87343b82"
navigation:
- title: About
  url: /about
- title: Resume
  url: /resume.pdf
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
